FROM ubuntu:18.04

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update && apt-get -y upgrade && \
    apt-get -y install \
    build-essential \
    libssl-dev \
    libffi-dev\
    vim \
    sudo \
    wget \
    git \
    unzip \
    htop

# install anaconda
# tensorflow doesn't support python3.7, so we have to stick to anaconda 5.2.0 whose python is version 3.6.
RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh

# notebook extensions + jupyter-vim-binding
RUN pip install --upgrade pip && \
    pip install \
    msgpack \
    jupyter_contrib_nbextensions && \
    jupyter contrib nbextensions install --user && \
    mkdir -p $(jupyter --data-dir)/nbextensions && \
    cd $(jupyter --data-dir)/nbextensions && \
    git clone https://github.com/lambdalisue/jupyter-vim-binding vim_binding

# for matplotlib Japanese font
WORKDIR /tmp
RUN curl -L  "https://oscdl.ipa.go.jp/IPAexfont/ipaexg00301.zip" > font.zip && \
    unzip font.zip && rm font.zip && \
    mv ipaexg00301/ipaexg.ttf /opt/conda/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/ipaexg.ttf && \
    rm -r ipaexg00301
RUN echo "font.family : IPAexGothic" >>  /opt/conda/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc
RUN rm -r ~/.cache
