FROM ryomazda/anaconda3:2019.07

# MeCab
RUN apt-get update && apt-get -y install \
    mecab \
    mecab-ipadic-utf8 \
    libmecab-dev \
    swig \
  && rm -rf /var/lib/apt/lists/*

# MeCab NEologd
# https://github.com/neologd/mecab-ipadic-neologd
WORKDIR /opt
RUN git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git && \
    cd mecab-ipadic-neologd && \
    ./bin/install-mecab-ipadic-neologd -n -y -a
# Configure dictionary for MeCab at /etc/mecabrc
ENV MECABRC="/etc/mecabrc"
RUN sed -i "s@/var/lib/mecab/dic/debian@/usr/lib/x86_64-linux-gnu/mecab/dic/mecab-ipadic-neologd@g" ${MECABRC}

# https://pypi.org/project/mecab-python3/
RUN pip install --upgrade pip && \
    pip install \
    mecab-python3



# go back to the home of the root
WORKDIR /root
