FROM ryomazda/anaconda3:5.3.0

# MeCab
# https://pypi.org/project/mecab-python3/
RUN apt-get update && apt-get -y upgrade && \
    apt-get -y install \
    mecab \
    mecab-ipadic-utf8 \
    libmecab-dev \
    swig
RUN pip install --upgrade pip && \
    pip install \
    mecab-python3

# CRF++ (for cabocha)
WORKDIR /opt
COPY CRF++-0.58.tar.gz /opt/CRF++-0.58.tar.gz
# RUN wget "https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7QVR6VXJ5dWExSTQ" -O CRF++-0.58.tar.gz
RUN tar zxvf CRF++-0.58.tar.gz && rm CRF++-0.58.tar.gz && cd CRF++-0.58/ && \
    ./configure && make && make install && ldconfig

# Cabocha
# https://qiita.com/woody-kawagoe/items/09c0f89a55701bcf72eb
WORKDIR /opt
# cabocha is on the google drive and it's annoying to download it through wget
COPY cabocha-0.69.tar.bz2 /opt/cabocha-0.69.tar.bz2
# Below may work but I don't wanna use it
# RUN wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=0B4y35FiV1wh7SDd1Q1dUQkZQaUU' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=0B4y35FiV1wh7SDd1Q1dUQkZQaUU" -O cabocha-0.69.tar.bz2 && rm -rf /tmp/cookies.txt
RUN tar xjvf cabocha-0.69.tar.bz2 && rm cabocha-0.69.tar.bz2 && cd cabocha-0.69 && \
    ./configure --with-charset=UTF8 --with-posset=IPA && make && make install && ldconfig

# python binding for cabocha
RUN cd cabocha-0.69/python && \
    python setup.py build_ext && \
    python setup.py install && \
    sudo ldconfig

# MeCab NEologd
# https://github.com/neologd/mecab-ipadic-neologd
WORKDIR /opt
RUN git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git && \
    cd mecab-ipadic-neologd && \
    ./bin/install-mecab-ipadic-neologd -n -y -a
# Configure dictionary for MeCab at /etc/mecabrc
RUN sed -i "s@/var/lib/mecab/dic/debian@/usr/lib/x86_64-linux-gnu/mecab/dic/mecab-ipadic-neologd@g" /etc/mecabrc

# go back to the home of the root
WORKDIR /root
