on:
  push:
    branches: [master]
  release:
    types: [published]
jobs:
  jupyterlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/build-push-action@v1
        with:
          path: jupyterlab
          username: ryomazda
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          target: jupyterlab
          repository: ryomazda/jupyterlab
      - uses: docker/build-push-action@v1
        with:
          path: jupyterlab
          username: ryomazda
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          target: japaterlab
          repository: ryomazda/japaterlab
      - uses: docker/build-push-action@v1
        with:
          path: jupyterlab
          username: ryomazda
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          target: nlp_course
          repository: ryomazda/nlp_course
  jupyterlab_cuda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/build-push-action@v1
        with:
          path: jupyterlab_cuda
          username: ryomazda
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          target: jupyterlab
          repository: ryomazda/jupyterlab_cuda
      - uses: docker/build-push-action@v1
        with:
          path: jupyterlab_cuda
          username: ryomazda
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          target: japaterlab
          repository: ryomazda/japaterlab_cuda
      - uses: docker/build-push-action@v1
        with:
          path: jupyterlab_cuda
          username: ryomazda
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          target: nlp_course
          repository: ryomazda/nlp_course_cuda
