name: build_push_docker
on: push
jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: jupyterlab
        uses: docker/build-push-action@v1
        with:
          path: jupyterlab
          username: ryomazda
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ryomazda/jupyterlab
          tag_with_ref: true
          target: jupyterlab
          tags: latest
      - name: jupyterlab
        uses: docker/build-push-action@v1
        with:
          path: jupyterlab
          username: ryomazda
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ryomazda/japaterlab
          tag_with_ref: true
          target: japaterlab
          tags: latest
