name: publish_docker
on:
  release:
    types: [published]
jobs:
  jupyterlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ryomazda/jupyterlab
          username: ryomazda
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: jupyterlab
          tag_names: true
